- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Updating apt
      command: sudo apt-get update

    - name: Install Java 11
      command: sudo apt-get install -y openjdk-11-jre
      become: yes

    - name: Install Maven
      command: sudo apt-get install -y maven=3.6.3-1
      become: yes

    - name: Install Docker
      command: sudo apt-get install -y docker.io
      become: yes

    - name: Start Docker Service
      command: sudo systemctl start docker
      become: yes
